  data_folder: /content/kits_preprocessed/

  runner_params:
    logdir: /content/logs/segmentation/
    num_epochs: 250
    fp16: False
    verbose: True

  io_params:
    test_size: 0.2
    split_seed: 42
    batch_size: 32
    num_workers: 2
    aug_key: resunet1
    # classes_per_slice_path is for when sample_on_the_fly is False
    classes_per_slice_path: ~ #/content/kits_preprocessed/classes_per_slice.json
    slice_indices_json_path: /content/kits_preprocessed/slice_indices.json
    sample_on_the_fly: True
    sampling_distribution:
      - 0.33
      - 0.33
      - 0.34
    pseudo_3D: True
    num_pseudo_slices: 5

  criterion_params:
    loss: CrossentropyND
    CrossentropyND:
      weight:
        - 0.3
        - 1.0
        - 3.0

  model_params:
    model_name: ResUNet
    ResUNet:
      input_channels: 5
      base_num_features: 16
      num_classes: 3
      num_pool: 4
      max_num_features: 256

  opt_params:
    opt: Adam
    Adam:
      lr: 0.0001
      weight_decay: 0.1
    scheduler_params:
      scheduler: ~

  callback_params:
    EarlyStoppingCallback:
      patience: 60
      min_delta: 0.001
    AccuracyCallback:
      activation: Softmax

    checkpoint_params:
      checkpoint_path: ~
      mode: model_only

  # specify if you want to save plotly plots as .pngs
  ## Requires separate installation of xvfb on Colab.
  # plot_params:
  #   metrics:
  #     - loss/epoch
  #     # - ppv/class_0/epoch
  #     # - f1/class_0/epoch
  #     # - tpr/class_0/epoch
  #   save_dir: /content/logs/segmentation/
